apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kubernetes.docker.internal
  #- host: kube-ingress.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-service 
          servicePort: http
      - path: /anotherservice
        backend:
          serviceName: frontend
          servicePort: http