version: "3.7"
services:
  mysql:
    image: mysql:8.0.22
    container_name: user-api-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    ports:
      - "3306:3306"
