#Storage Class
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner   #node provisioner
#volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true                  #other otpions is false. Determines whether to expand/resize the volume that created


#Persistent Volume
#you dont actually have to create a storage class. Simply mentioning here will automatically provision it. 
#But if want control like allowVolumeExpansion create a Storageclass
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: local-storage #storage class referred here
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/C/Users/Kavutham/Documents/tempgit/Dum
    type: Directory

#persistentVolumeReclaimPolicy: Recycle ---> otheroptions are Retain,Delete,Recycle
#Retain: Keeps all data. Requires adminstrator to clean up all data manually to prepare PV to reused.
#Delete: Deletes the underlying storage resource automatically (only works for cloud)
#Recylce: Automatically deletes only the data in the underlying storage allowing PV to be used again


#PersistenVolumeClaim 
#You can expand the PVC without interrupting the application. Keep in mind to keep storage class allowVolumeExpansion is set to true
#PVC will automatically will be bound to PV based on the spec provided
# PV with status available: Not bound yet and ready to be used. Status=bound says it is attached to PV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: local-storage
  volumeName: my-pv
  accessModes:
  - ReadWriteMany  #it needs to match to PV and PVC
  resources:
    requests:
      storage: 100Mi #provision based on the PV total storage. Provide less that 1Gi # Empty string must be explicitly set otherwise default StorageClass will be set

#Pod:
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', "while :; do echo Success! > /output/success.txt; sleep 5 ; done"]
    volumeMounts:
    - name: pv-volume
      mountPath: /output #mounting the volume to this path in container
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: my-pvc #pvc we created earlier is referred have