apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  restartpolicy: Never
  containers:
  - name: busybox1
    image: busybox
    command: ['/bin/sh','-c','while true; do echo Sucess! > /output/success.txt; sleep 5; done']
    volumMounts:
    - name: cache-volume
      mountPath: /output
  - name: busybox2
    image: busybox
    command: ['/bin/sh','-c','while true; do cat /input/success.txt; sleep 5; done']
    volumeMounts:
    - name: cache-volume
      mountPath: /input
  volumes:
  - name: cache-volume
    emptyDir: {}


# kubectl logs shared-volume-pod -c busybox2