pipeline {
    agent any
    options { checkoutToSubdirectory('/Jenkins/Gradle_pipeline')
    stages {
        stage('clean') {
            steps {
                bat 'gradle clean'
            }
        }
		stage('Build') {
            steps {
                bat 'gradle build'
            }
        }
        stage('Test') {
            steps {
                bat 'gradle test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deployed Successfully'
            }
        }
    }
}
