apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  #type: NodePort
  ports:
  - name: http
    port: 87
    targetPort: 80
  #ports:
  #- port: 87
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend