apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - name: http
    port: 84
    targetPort: 80
    nodePort: 30020
  selector:
    app: web