apiVersion: v1
kind: Service
metadata:
  name: shipping-svc
spec:
  selector:
    app: shipping-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: shipping-backend
  labels:
    name: shipping-svc
spec:
  containers:
  - name: nginix
    image: nginix:1.91.1