version: '3'

services:
  product-service:
    container_name: backend # if not specified will automatically create a container name with foldername_servicename
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    expose:
      - 80 #expose is diff from port(not applicable to host netwrk). only internal port is exposed without publishing to host machine
    depends_on:
      - product-service
    deploy:  #only available in version 3.
      replicas: 2
      resources: #set resource limit for cpu and memory
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 20M
          
  nginx:  #act as a load balancer that forwards requests from 4000 to 5001 port of backend app. added nginx conf file as well
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - website
    ports:
      - "4000:4000"